version: '3'
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  vote-app:
    image: vote-app-image  # Use the image name built in Step 1
    deploy:
      replicas: 4
      placement:
        max_replicas_per_node: 2
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
  
  postgres-db:
    image: "postgres"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
  
  worker-app:
    image: worker-app-image  # Use the image name built in Step 1
    container_name: worker

  results-app:
    image: results-app-image  # Use the image name built in Step 1
    ports:
      - "8090:80"
